### PR TITLE
Add a GitHub action to check if version needs bumping

### PR DESCRIPTION
**Pull request by kmpaul**
There are methods to make bumping versions of software easy, but as far as I know there is no good way to make sure that your current version (i.e., the one listed in your software source) can be published on PyPI without conflict.  That is, how can you check to see if your current software version can be released on PyPI without conflict? 

Well, the steps to do this are pretty easy and this PR implements and action to check if the current source version of the software has been "bumped" to a version greater than the one findable on PyPI.  If the current source version is not greater than the latest published version, then the check will fail with a message saying you need to bump your version.

### CODE REVIEW

**Comment by kmpaul** [comment]
CC @andersy005 @mgrover1 @jukent 

If I used **setuptools-scm** this would be unnecessary, right?  With **setuptools-scm**, the detectable software version would be changed once a new git tag is created, right?  So, if I were to create a new tag/release on GitHub, then the version built by the `pypa/gh-action-pypi-publish` GitHub action would match the newly created tag, right?

If so, then I'm going to close this PR and just setup **setuptools-scm** in this package.

**Comment by dopplershift** [comment]
@kmpaul Yes, setuptools-scm can generate your version from the closest git tag (see `git describe --tags`).

**Comment by kmpaul** [comment]
Great!  Thanks, @dopplershift!  I was hoping to hear that before spending the time to investigate. I'll not merge this PR then and, instead, implement a `setuptools-scm` solution.

**Comment by kmpaul** [comment]
Closing this PR in favor of #24.

**Pull request closed without merging**
