### PR TITLE
Create a jupyter book demo with sphinx-pythia-theme

### PR DESCRIPTION
**Pull request by halehawk**
Modify the followings in sphinx-pythia-theme 
- sidebar button text-align left
- sidebar scrollable
- add notebook in demo and sphinx-build successfully
- add jupyter book demo as jb_demo, and jb build sucessfully

### CODE REVIEW

**Comment by brian-rose** [comment]
@kmpaul does this PR help address #7?

**Comment by kmpaul** [comment]
I haven't tested it, but I'm concerned about the "sidebar scrollable" fix.  I'll try to take a look at this PR today and give a more detailed review.

**Comment by ktyle** [comment]
As part of my self-education in Sphinx, I was able to do a jupyterbook build and visualize the output of this PR. I'm not sure if this is related to @kmpaul 's concern above, but I notice that the sidebar obscures some of the content in the main frame. See attached screenshot. 
sphinx-pythia-theme_screenshot

**Comment by halehawk** [comment]
I thought this will be solved if there are enough contents on this Pandas page.

Haiying

**Comment by kmpaul** [comment]
@halehawk:  You can't always guarantee that will be true.  I suggest that the "fixed" attribute of the sidebar be removed and let the sidebar scroll with the main page.  It is not as convenient as having it float above the content like the top navbar does, but it resolves this problem in a fairly professional way.

**Comment by halehawk** [comment]
Even if I removed the scrollable sidebar that I added on, this problem that
Kevin Tyle pointed out is still there. Because you set the footer as the
attached image.

**Comment by halehawk** [comment]
The footer is along the whole bottom, because the sidebar can be collapsed,
then you can see the whole bottom.

**Pull request closed without merging**
